"""Build data/weekly.js from content/weekly/*.json, and place the decks in the site.

The authored file carries one entry per slide (a short label + a written summary).
This validates it, copies the original deck into docs/library/weekly/, and emits
the data file the Weekly Classes view reads.

Validation that matters:
  · every slide after the skipped title/TOC slides has a label and a summary
  · the slide numbers present match the deck's real page count
  · a Khmer label is only shipped when it is free of the source PDF's known
    glyph-substitution artefacts (the deck's own text layer is corrupt; a label
    that carries one of those artefacts would go out garbled)

Run:  python tools/build_weekly.py
"""
import json
import pathlib
import re
import shutil
import sys

sys.stdout.reconfigure(encoding="utf-8")
ROOT = pathlib.Path(__file__).resolve().parents[1]
CONTENT = ROOT / "content" / "weekly"
SITE = ROOT / "docs"

# artefacts of the legacy KhmerOS subsets in these decks: a label containing one of
# these would render as broken Khmer, so such a label is dropped rather than shipped
BAD = ["អនតរ", "កនុង", "ដលែ", "ដដ្យ", "ប្ប", "សប្ា", "នន", "ចាប់កនុង", "ដ្ឋា", "រឋែ", "ប្បៃ", "ដ្នក"]

problems, notes = [], []


def khmer_ok(s):
    return not any(b in s for b in BAD)


def main() -> int:
    weeks = []
    for path in sorted(CONTENT.glob("*.json")):
        w = json.loads(path.read_text(encoding="utf-8"))
        wid = w["id"]
        pages = w["pages"]
        skip = set(w.get("skip") or [])

        # 1. the deck must be in the site, byte-identical to the source
        src = pathlib.Path(w["src"])
        dest = SITE / w["deck"]
        if not src.exists():
            problems.append(f"{wid}: source deck not found: {src}")
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            if not dest.exists() or dest.stat().st_size != src.stat().st_size:
                shutil.copy2(src, dest)
            notes.append(f"  {wid}: deck -> {w['deck']} ({dest.stat().st_size // 1024} KB)")

        # 2. the slide list must cover exactly the slides that are not skipped
        want = [n for n in range(1, pages + 1) if n not in skip]
        got = [s["n"] for s in w["slides"]]
        if got != want:
            missing = [n for n in want if n not in got]
            extra = [n for n in got if n not in want]
            problems.append(f"{wid}: slide list mismatch (missing {missing}, unexpected {extra})")

        # 3. every slide needs a label and a summary, and a clean Khmer label
        for s in w["slides"]:
            if not (s.get("en") or "").strip():
                problems.append(f"{wid} slide {s['n']}: no English label")
            if len((s.get("summary") or "").strip()) < 40:
                problems.append(f"{wid} slide {s['n']}: summary missing or too short")
            km = (s.get("km") or "").strip()
            if km and not khmer_ok(km):
                problems.append(f"{wid} slide {s['n']}: Khmer label carries source artefacts "
                                f"({[b for b in BAD if b in km]}) — must be fixed or dropped")

        weeks.append({
            "id": wid,
            "title": w["title"],
            "topic": w.get("topic"),
            "deck": w["deck"],
            "pages": pages,
            "skip": sorted(skip),
            "note": w.get("note"),
            "source": w.get("source"),
            "slides": [
                {"n": s["n"], "km": s.get("km", ""), "en": s["en"], "summary": s["summary"]}
                for s in w["slides"]
            ],
        })
        notes.append(f"  {wid}: {len(w['slides'])} slides with summaries "
                     f"(skipped {sorted(skip)} of {pages})")

    if not weeks:
        problems.append("no weekly content found in content/weekly/")

    out = SITE / "data" / "weekly.js"
    body = json.dumps({"weeks": weeks}, ensure_ascii=False, indent=1)
    out.write_text("/* generated by tools/build_weekly.py — do not edit by hand */\n"
                   "window.IPL_WEEKLY = " + body + ";\n", encoding="utf-8")
    notes.append(f"  wrote {out.relative_to(ROOT)} ({out.stat().st_size // 1024} KB)")

    print("\n".join(notes))
    if problems:
        print(f"\n{len(problems)} problem(s):")
        for p in problems:
            print("  ✗", p)
        return 1
    print("\nweekly data ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
