"""Merge content/*.json into the site data files, validating every quote against
the decoded source text (anti-hallucination check)."""
import json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CONTENT = ROOT / "content"
SITE = ROOT / "site"
DATA = SITE / "data"
DATA.mkdir(parents=True, exist_ok=True)

def norm(s):
    s = str(s or "")
    s = s.replace("\u200b", "")
    s = re.sub(r"[\s\u00a0]+", "", s)
    return s

BOOK = norm((ROOT / "extracted" / "textbook_decoded.md").read_text(encoding="utf-8"))
REFS = {
    "en-eccc": norm((ROOT / "extracted" / "chapters" / "ref-eccc.txt").read_text(encoding="utf-8")),
    "en-paris": norm((ROOT / "extracted" / "chapters" / "ref-paris.txt").read_text(encoding="utf-8")),
}
BOOK_ALL = BOOK + REFS["en-eccc"] + REFS["en-paris"]

ORDER = {"ch1": 1, "ch2": 2, "ch3": 3, "ch4": 4, "ch5": 5, "ch6": 6, "ch7": 7, "ch8": 8,
         "ref-eccc": 9, "ref-paris": 10}

chapters = {}
problems = []
stats = {"quotes": 0, "quotes_ok": 0, "terms": 0, "questions": 0, "lessons": 0}

files = sorted(p for p in CONTENT.glob("*.json") if not p.name.startswith("_"))
if not files:
    print("no content files yet")
for path in files:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:
        problems.append(f"{path.name}: INVALID JSON ({e})")
        continue
    items = raw if isinstance(raw, list) else [raw]
    for obj in items:
        cid = obj.get("id")
        if not cid:
            problems.append(f"{path.name}: object without id")
            continue
        if cid in chapters:
            base = chapters[cid]
            base["lessons"].extend(obj.get("lessons", []))
            if not base.get("summary", {}).get("km") and obj.get("summary"):
                base["summary"] = obj["summary"]
            for key in ("pages",):
                if obj.get(key):
                    base[key] = obj[key]
        else:
            chapters[cid] = obj

# validate + normalise
for cid, ch in chapters.items():
    ch["num"] = ORDER.get(cid, ch.get("num", 0))
    ch["lessons"] = sorted(ch.get("lessons", []), key=lambda l: (l.get("pages", {}).get("from") or 0))
    for l in ch["lessons"]:
        stats["lessons"] += 1
        for qt in l.get("quotes", []):
            stats["quotes"] += 1
            txt = qt.get("km") if qt.get("srcLang") != "en" else qt.get("en")
            hay = BOOK_ALL
            if qt.get("srcLang") == "en":
                hay = REFS["en-eccc"] + REFS["en-paris"]
            if txt and norm(txt) in hay:
                stats["quotes_ok"] += 1
            else:
                problems.append(f"{cid}/{l.get('id')}: quote not found in source (p.{qt.get('page')}): {str(txt)[:60]}")
        stats["terms"] += len(l.get("terms", []))
        stats["questions"] += len(l.get("quiz", []))

ordered = [chapters[k] for k in sorted(chapters, key=lambda c: ORDER.get(c, 99))]

(DATA / "lessons.js").write_text(
    "/* generated by tools/build_site_data.py — do not edit by hand */\n"
    "window.IPL_CHAPTERS = " + json.dumps(ordered, ensure_ascii=False, indent=0) + ";\n",
    encoding="utf-8")

corpus_path = ROOT / "site" / "data" / "corpus.json"
if "--quotes-only" in sys.argv:
    # reduced, quotation-only corpus: lesson quotes, key points and terms with page refs
    reduced = []
    for ch in ordered:
        for l in ch.get("lessons", []):
            page = (l.get("pages") or {}).get("from")
            for qt in l.get("quotes", []):
                if qt.get("km") or qt.get("en"):
                    reduced.append({"src": "textbook" if qt.get("srcLang") != "en" else "eccc",
                                    "lang": qt.get("srcLang") or "km", "page": qt.get("page") or page,
                                    "text": (qt.get("km") or "") + ("\n" + qt["en"] if qt.get("en") else "")})
            pts = (l.get("keyPoints") or {})
            for km, en in zip(pts.get("km", []), pts.get("en", [])):
                reduced.append({"src": "textbook", "lang": "km", "page": page, "text": km + ("\n" + en if en else "")})
    corpus = reduced
    print(f"quotes-only corpus: {len(corpus)} passages")
else:
    corpus = json.loads(corpus_path.read_text(encoding="utf-8"))
(DATA / "corpus.js").write_text(
    "/* generated from the three source documents */\n"
    "window.IPL_CORPUS = " + json.dumps(corpus, ensure_ascii=False, separators=(",", ":")) + ";\n",
    encoding="utf-8")

print(f"chapters: {len(ordered)}  lessons: {stats['lessons']}  terms: {stats['terms']}  quiz Q: {stats['questions']}")
print(f"quotes: {stats['quotes_ok']}/{stats['quotes']} verified verbatim in the sources")
print(f"corpus: {len(corpus)} passages ({(DATA / 'corpus.js').stat().st_size/1024:.0f} KB), lessons.js {(DATA / 'lessons.js').stat().st_size/1024:.0f} KB")
if problems:
    print(f"\n{len(problems)} problems:")
    for p in problems[:40]:
        print("  -", p)
